apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name | dump }}
  annotations:
    github.com/project-slug: victor-ribamar-verzel/EC2-AWS
  description: ${{ values.name }} AWS Infra EC2 + S3
spec:
  type: service
  owner: user:guest
  lifecycle: experimental
